name: "Docker Build"

on:
  workflow_dispatch: {}
  push:
    tags:
      - "v*"

jobs:
  docker-build-voidmerge-server:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/voidmerge/voidmerge-server
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          file: docker/voidmerge-server/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
